"""
netlist_parser.py
-----------------
Parse SPICE-style netlists (as generated by AnalogCoderPro) into
Text-Attributed Graphs (TAGs) compatible with PyTorch Geometric.

Each node  = a circuit component with a rich text attribute
Each edge  = an electrical connection (shared net)
Graph-level labels can be circuit performance metrics from ngspice output.
"""

import re
from dataclasses import dataclass, field
from typing import Optional
import torch
from torch_geometric.data import Data


# ─────────────────────────────────────────────
# Component type metadata
# ─────────────────────────────────────────────

COMPONENT_META = {
    "R": {"full_name": "Resistor",        "unit": "Ohm",    "role": "passive"},
    "C": {"full_name": "Capacitor",       "unit": "Farad",  "role": "passive"},
    "L": {"full_name": "Inductor",        "unit": "Henry",  "role": "passive"},
    "M": {"full_name": "MOSFET",          "unit": None,     "role": "active"},
    "Q": {"full_name": "BJT",             "unit": None,     "role": "active"},
    "D": {"full_name": "Diode",           "unit": None,     "role": "active"},
    "V": {"full_name": "Voltage Source",  "unit": "Volt",   "role": "source"},
    "I": {"full_name": "Current Source",  "unit": "Ampere", "role": "source"},
    "E": {"full_name": "VCVS",            "unit": None,     "role": "controlled"},
    "F": {"full_name": "CCCS",            "unit": None,     "role": "controlled"},
    "G": {"full_name": "VCCS",            "unit": None,     "role": "controlled"},
    "H": {"full_name": "CCVS",            "unit": None,     "role": "controlled"},
    "X": {"full_name": "Subcircuit",      "unit": None,     "role": "subckt"},
}

ROLE_TO_IDX = {"passive": 0, "active": 1, "source": 2, "controlled": 3, "subckt": 4, "unknown": 5}

# SPICE engineering suffixes
SUFFIX_MAP = {
    "f": 1e-15, "p": 1e-12, "n": 1e-9, "u": 1e-6,
    "m": 1e-3,  "k": 1e3,   "meg": 1e6, "g": 1e9,
    "t": 1e12,
}


def parse_spice_value(val_str: str) -> Optional[float]:
    """Convert SPICE value string (e.g. '10k', '2.2u', '1meg') to float."""
    val_str = val_str.lower().strip()
    for suffix, mult in sorted(SUFFIX_MAP.items(), key=lambda x: -len(x[0])):
        if val_str.endswith(suffix):
            try:
                return float(val_str[: -len(suffix)]) * mult
            except ValueError:
                return None
    try:
        return float(val_str)
    except ValueError:
        return None


# ─────────────────────────────────────────────
# Data classes
# ─────────────────────────────────────────────

@dataclass
class Component:
    name: str           # e.g. "R1", "M3"
    ctype: str          # e.g. "R", "M"
    nets: list[str]     # connected net names
    params: dict        # raw parameter dict
    text_attr: str = "" # rich text description (TAG node feature)
    role_idx: int = 5   # numeric role label


@dataclass
class CircuitGraph:
    components: list[Component] = field(default_factory=list)
    net_map: dict = field(default_factory=dict)     # net_name -> list of comp indices
    title: str = ""
    performance: dict = field(default_factory=dict) # optional metric labels


# ─────────────────────────────────────────────
# Text attribute builder
# ─────────────────────────────────────────────

def build_text_attr(comp: Component) -> str:
    """
    Build a natural-language text description for a component.
    This is the 'text' in the Text-Attributed Graph node.

    Examples:
      "Resistor R1 with resistance 10.0 kΩ, connected to nets [vdd, out]"
      "MOSFET M1 (NMOS) with W=2.0 µm L=0.18 µm, connected to nets [drain, gate, source, body]"
    """
    meta = COMPONENT_META.get(comp.ctype, {"full_name": f"Unknown({comp.ctype})", "unit": None, "role": "unknown"})
    full_name = meta["full_name"]
    unit = meta["unit"]

    desc_parts = [f"{full_name} {comp.name}"]

    # Passive components: main value
    if comp.ctype in ("R", "C", "L") and "value" in comp.params:
        val = parse_spice_value(comp.params["value"])
        unit_str = unit or ""
        if val is not None:
            # Pretty-print with SI prefix
            for suffix, mult in [("T", 1e12), ("G", 1e9), ("M", 1e6), ("k", 1e3),
                                  ("", 1), ("m", 1e-3), ("µ", 1e-6), ("n", 1e-9),
                                  ("p", 1e-12), ("f", 1e-15)]:
                if abs(val) >= mult or mult == 1e-15:
                    desc_parts.append(f"with {comp.ctype.lower()} = {val/mult:.3g} {suffix}{unit_str}")
                    break
        else:
            desc_parts.append(f"value={comp.params['value']}")

    # MOSFET: model, W, L
    elif comp.ctype == "M":
        model = comp.params.get("model", "unknown_model")
        # Infer NMOS/PMOS from model name or 'type' param
        mos_type = "PMOS" if any(s in model.lower() for s in ["p", "pmos"]) else "NMOS"
        desc_parts.append(f"({mos_type}, model={model})")
        for param in ("w", "l", "ad", "as"):
            if param in comp.params:
                desc_parts.append(f"{param.upper()}={comp.params[param]}")

    # BJT: model, type
    elif comp.ctype == "Q":
        model = comp.params.get("model", "unknown")
        desc_parts.append(f"(model={model})")

    # Voltage/current sources
    elif comp.ctype in ("V", "I"):
        src_type = comp.params.get("src_type", "DC")
        if src_type == "DC" and "dc_value" in comp.params:
            desc_parts.append(f"DC {comp.params['dc_value']} {unit}")
        elif src_type == "AC":
            desc_parts.append(f"AC {comp.params.get('ac_mag', '')} {unit}")
        elif src_type == "PULSE":
            desc_parts.append(f"PULSE waveform {unit}")
        elif src_type == "SIN":
            desc_parts.append(f"SINUSOIDAL {comp.params.get('amplitude', '')} {unit} @ {comp.params.get('frequency', '')} Hz")
        else:
            desc_parts.append(f"{src_type} source")

    # Net connections
    net_str = ", ".join(f"[{n}]" for n in comp.nets[:4])
    desc_parts.append(f"connected to nets: {net_str}")

    return ", ".join(desc_parts)


# ─────────────────────────────────────────────
# SPICE netlist parser
# ─────────────────────────────────────────────

def _parse_mosfet_line(tokens: list[str]) -> tuple[list[str], dict]:
    """Parse MOSFET line: M<name> drain gate source body model [params]"""
    nets = tokens[:4]      # drain, gate, source, body
    model = tokens[4] if len(tokens) > 4 else "unknown"
    params = {"model": model}
    for token in tokens[5:]:
        if "=" in token:
            k, v = token.split("=", 1)
            params[k.lower()] = v.lower()
    return nets, params


def _parse_bjt_line(tokens: list[str]) -> tuple[list[str], dict]:
    """Parse BJT line: Q<name> collector base emitter [substrate] model"""
    nets = tokens[:3]
    model = tokens[3] if len(tokens) > 3 else "unknown"
    # optional substrate
    if len(tokens) > 4 and "=" not in tokens[3]:
        nets = tokens[:4]
        model = tokens[4]
    params = {"model": model}
    return nets, params


def _parse_source_line(tokens: list[str]) -> tuple[list[str], dict]:
    """Parse V/I source line."""
    nets = tokens[:2]
    params = {}
    rest = tokens[2:]
    if not rest:
        return nets, params
    upper_rest = [t.upper() for t in rest]
    if "PULSE" in upper_rest:
        params["src_type"] = "PULSE"
    elif "SIN" in upper_rest or "SINE" in upper_rest:
        params["src_type"] = "SIN"
        # Try to extract freq/amplitude from SIN(...) or positional
        sin_str = " ".join(rest)
        m = re.search(r"SIN\s*\(\s*([\d.e+\-]+)\s+([\d.e+\-\w]+)\s+([\d.e+\-\w]+)", sin_str, re.I)
        if m:
            params["offset"] = m.group(1)
            params["amplitude"] = m.group(2)
            params["frequency"] = m.group(3)
    elif "AC" in upper_rest:
        params["src_type"] = "AC"
        idx = upper_rest.index("AC")
        if idx + 1 < len(rest):
            params["ac_mag"] = rest[idx + 1]
    else:
        params["src_type"] = "DC"
        # First numeric-ish token is the DC value
        for t in rest:
            if re.match(r"^[\d.+\-e]", t):
                params["dc_value"] = t
                break
    return nets, params


def parse_netlist(netlist_text: str) -> CircuitGraph:
    """
    Parse a SPICE netlist string into a CircuitGraph.

    Handles:
    - R, C, L (passive)
    - M (MOSFET), Q (BJT), D (Diode)
    - V, I sources (DC, AC, PULSE, SIN)
    - Line continuation with '+'
    - Inline comments with '$' or ';'
    """
    cg = CircuitGraph()
    lines = netlist_text.strip().splitlines()

    # Handle title line
    if lines:
        cg.title = lines[0].strip()
        lines = lines[1:]

    # Join continuation lines
    joined = []
    for line in lines:
        line = re.sub(r"[$;].*", "", line).strip()  # strip comments
        if not line or line.startswith("*"):
            continue
        if line.startswith("+") and joined:
            joined[-1] += " " + line[1:].strip()
        else:
            joined.append(line)

    for line in joined:
        tokens = line.split()
        if not tokens:
            continue
        name = tokens[0].upper()
        ctype = name[0]
        rest = tokens[1:]

        if ctype not in COMPONENT_META:
            continue  # skip .subckt, .end, .model, .tran, etc.

        comp = Component(name=name, ctype=ctype, nets=[], params={})
        meta = COMPONENT_META[ctype]
        comp.role_idx = ROLE_TO_IDX.get(meta["role"], 5)

        if ctype == "M":
            comp.nets, comp.params = _parse_mosfet_line(rest)
        elif ctype == "Q":
            comp.nets, comp.params = _parse_bjt_line(rest)
        elif ctype in ("V", "I"):
            comp.nets, comp.params = _parse_source_line(rest)
        elif ctype == "D":
            comp.nets = rest[:2]
            comp.params = {"model": rest[2]} if len(rest) > 2 else {}
        elif ctype in ("R", "C", "L"):
            comp.nets = rest[:2]
            comp.params = {"value": rest[2]} if len(rest) > 2 else {}
        elif ctype in ("E", "F", "G", "H"):
            comp.nets = rest[:4] if len(rest) >= 4 else rest
            comp.params = {"gain": rest[4]} if len(rest) > 4 else {}
        elif ctype == "X":
            # Subcircuit: last token is subckt name, rest are nets
            comp.nets = rest[:-1]
            comp.params = {"subckt": rest[-1]} if rest else {}
        else:
            comp.nets = rest[:2]

        comp.text_attr = build_text_attr(comp)
        cg.components.append(comp)

    # Build net_map
    for idx, comp in enumerate(cg.components):
        for net in comp.nets:
            if net not in cg.net_map:
                cg.net_map[net] = []
            cg.net_map[net].append(idx)

    return cg


# ─────────────────────────────────────────────
# TAG → PyG Data
# ─────────────────────────────────────────────

def circuit_graph_to_pyg(
    cg: CircuitGraph,
    text_encoder=None,
    performance_keys: Optional[list[str]] = None,
) -> Data:
    """
    Convert a CircuitGraph into a PyTorch Geometric Data object.

    Args:
        cg: parsed CircuitGraph
        text_encoder: callable(list[str]) -> Tensor  [N, d_text]
                      If None, stores raw text_attrs as a list (for LM encoding later).
        performance_keys: which performance metrics to include as graph-level y.

    Returns:
        PyG Data with:
          data.x_text  : list of text descriptions per node (raw)
          data.x       : encoded text features [N, d] if encoder provided
          data.edge_index : [2, E]
          data.role    : [N] integer role labels
          data.node_names: list of component names
          data.y       : performance vector (if provided)
    """
    n = len(cg.components)
    if n == 0:
        return Data()

    text_attrs = [c.text_attr for c in cg.components]
    roles = torch.tensor([c.role_idx for c in cg.components], dtype=torch.long)
    node_names = [c.name for c in cg.components]

    # Build edges via shared nets (undirected)
    src_list, dst_list = [], []
    for net, comp_indices in cg.net_map.items():
        if net.lower() in ("0", "gnd", "vss"):
            # Ground net: still connect components that share ground
            pass
        for i in range(len(comp_indices)):
            for j in range(i + 1, len(comp_indices)):
                u, v = comp_indices[i], comp_indices[j]
                src_list += [u, v]
                dst_list += [v, u]

    if src_list:
        edge_index = torch.tensor([src_list, dst_list], dtype=torch.long)
    else:
        edge_index = torch.zeros((2, 0), dtype=torch.long)

    # Encode text if encoder provided
    if text_encoder is not None:
        x = text_encoder(text_attrs)
    else:
        x = None  # will be populated externally

    # Performance labels
    y = None
    if performance_keys and cg.performance:
        vals = [cg.performance.get(k, float("nan")) for k in performance_keys]
        y = torch.tensor(vals, dtype=torch.float).unsqueeze(0)

    data = Data(
        edge_index=edge_index,
        role=roles,
        num_nodes=n,
    )
    data.x_text = text_attrs   # raw text (list)
    data.node_names = node_names
    if x is not None:
        data.x = x
    if y is not None:
        data.y = y

    return data


# ─────────────────────────────────────────────
# Quick sanity test
# ─────────────────────────────────────────────

if __name__ == "__main__":
    sample_netlist = """
Two-Stage Op-Amp
* Power supply
VDD vdd 0 DC 1.8
VSS vss 0 DC -1.8
* Input differential pair
M1 vout1 vin+ vs1 vss NMOS W=10u L=0.18u
M2 vout2 vin- vs1 vss NMOS W=10u L=0.18u
* Tail current source
M3 vs1 vbias vss vss NMOS W=5u L=0.5u
* Load mirrors
M4 vout1 vout1 vdd vdd PMOS W=20u L=0.18u
M5 vout2 vout1 vdd vdd PMOS W=20u L=0.18u
* Second stage
M6 vout vout2 vss vss NMOS W=40u L=0.18u
M7 vout vbias2 vdd vdd PMOS W=80u L=0.18u
* Miller compensation
CC vout2 vout 3p
RC vout2 rc_mid 200
* Bias resistor
RBIAS vbias 0 100k
* Load
CL vout 0 10p
"""
    cg = parse_netlist(sample_netlist)
    print(f"Parsed {len(cg.components)} components, {len(cg.net_map)} nets\n")
    for comp in cg.components:
        print(f"  {comp.name:8s} | {comp.text_attr}")

    print("\n--- PyG conversion ---")
    data = circuit_graph_to_pyg(cg)
    print(f"  Nodes : {data.num_nodes}")
    print(f"  Edges : {data.edge_index.shape[1]}")
    print(f"  Roles : {data.role.tolist()}")
